# Generated by Django 5.1.3 on 2025-01-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body1', models.TextField(blank=True)),
                ('body2', models.TextField(blank=True)),
                ('body3', models.TextField(blank=True)),
                ('body4', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
