# Generated by Django 5.1.3 on 2025-01-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_myevent_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myevent',
            old_name='datetime',
            new_name='date',
        ),
    ]
