# Generated by Django 5.1.3 on 2025-01-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_datetime_myevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myevent',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
