# Generated by Django 5.1.3 on 2025-01-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_myevent_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myevent',
            name='slug',
            field=models.SlugField(),
        ),
    ]
